### ISSUE TITLE
Closing a connection when there are pending operations

### ISSUE THREAD

**Issue by hoylen** [wstrange/dartdap#12]
I'm currently modifying the `LDAPconnection` class to automatically re-open disconnected connections. This is useful for dealing with LDAP directory servers which timesout idle connections, or with network disconnections (assuming the network is somehow reconnected before the next LDAP operation is performed; for example, if the LDAP directory server was restarted). This feature will allow an LDAP connection to be truly long-lived: open once and just keep it.

The lower-level `ConnectionManager` class in _connection_manager.dart_  has this `close` method:

``` dart
  Future close(bool immediate) {
    if (immediate || _canClose()) {
      return _doClose();
    } else {
      var c = new Completer();
      // todo: dont wait if there are no pending ops....
      new Timer.periodic(PENDING_OP_TIMEOUT, (Timer t) {
        if (_canClose()) {
          t.cancel();
          _doClose().then((_) => c.complete());
        }
      });
      return c.future;
    }
  }
```
1. I'm confused by the **TODO** comment. Isn't the if-statement test for `_canClose` already detecting if there are pending operations? That is, the code has already been written and the TODO comment can be deleted.
2. I'm also wondering if the periodic PENDING_OP_TIMEOUT delays (3 seconds each time) can be replaced by having this method creating a new _Completer_ and then returning its _Future_ -- it is marked as completed by the code that removes pending messages off the queue, when the last message is removed from the queue?
3. I now have code that detects when the bytes to LDAP message transformer stream receives a "done" event (invoked by the underlying socket receiving a "done" event). Probably the close methods (the one on the higher-level LDAPconnection) should wait for that to happen, before the Future it returns completes. I don't think this matters from a functional point of view, but when logging is enabled it looks weird to have activity going on (i.e. the done event occurs) briefly after when you think the connection has been closed.

Supporting automatic connections is a breaking change, so I'm going to take the opportunity to rename "LDAPConnection" to "LdapConnection" to follow the [Dart convention for class names](https://www.dartlang.org/effective-dart/style/#identifiers).

**Comment by wstrange** [comment]
Hoylen,

doClose() /  _canClose()  -  it has been so long since I looked at this. I think it is just poorly written. The intent was to sleep a bit and keep checking until the last Opcode response is handled before  closing the underlying socket. If there is a way to wait on final drain of the queue that would be better. I believe the todo comment is just saying we are sleeping here even when it is not required. My recollection was that I ran into problems on the server on socket close - so the sleep loop fixed those.  This logic needs to be cleaned up...

Renaming LDAPConnection -  +1 

Automatically re-opening connection: Sounds like a useful feature.  I know some Java implementations create a separate connection pool class for this feature.  I can perhaps imagine a few cases where clients might not want this behaviour - so it should be optional I would think 

Thanks for your work on this!

**Comment by hoylen** [comment]
Yes, the new _automatic mode_ is optional. On by default, but you can turn it off at anytime (via the constructor or afterwards); or turn it back on at anytime.

When it is turned off, the program using the package is responsible for opening and binding connections; and re-opening connections if for some reason (e.g. server timeouts) the connections gets disconnected. There is new _state_ method for it to test if the connection is disconnected, since if/when it happens could be outside the control of the application.

When turned off, how the package is used is very similar to the way it is currently used, but with a few differences:
- The _search_ method returns a _Future_ to a _SearchResult_ instead of a _SearchResult_ directly. That's so it can asynchronously open and/or bind a connection, if needed. If the connection is already ready to use, the Future completes immediately and otherwise behaves like it does currently.
- There is a new _setAuthentication_ method for setting the Bind DN and password, and the behaviour of _bind_ has changed slightly. That's so they both can do sensible things in either automatic mode or manual mode.
- All the operations (e.g. add, delete, search) can throw additional exceptions. Mostly because if it needs to automatically open and/or bind the connection, before performing the operation, and that fails.

**Comment by hoylen** [comment]
Issue #13 has highlighted a need for a unit test for when _close_ is called with pending operations on the queue. I'll include such a unit test with the coming "automatic mode" code.
