### ISSUE TITLE
connection.close always cause Connection reset by peer

### ISSUE THREAD

**Issue by mlesin** [wstrange/dartdap#20]
During call of `await connection.close()` in finally block of the example, I always getting Connection reset by peer exception generated by LDAP stream transformer.
I thought maybe I need to close stream prior to closing connection, but even without any search queries, with only one explicit `connection.bind()` behaviour stays the same...
```
FINE: 2018-11-10 22:26:13.422664: close
FINEST: 2018-11-10 22:26:13.423224: close: started
FINEST: 2018-11-10 22:26:13.425320: wait for message stream to be done
SEVERE: 2018-11-10 22:26:13.469022: LDAP stream transformer: error=SocketException: OS Error: Connection reset by peer, errno = 54, address = dc.mydomain.com, port = 50844
FINER: 2018-11-10 22:26:13.469475: listen: onError
FINEST: 2018-11-10 22:26:13.470519: LDAP stream transformer: byte stream done
```

**Comment by mlesin** [comment]
I'm not sure if it's correct, but if I change `_socket.close()` to `_socket.destroy()` in `connection_manager.dart`, everything completes with no error. But I don't know if it is good to do this way or not.

**Comment by wstrange** [comment]
From reading  https://api.dartlang.org/stable/2.0.0/dart-io/Socket/destroy.html 

I think destroy is what we want - since it kills the socket for read and write.

I'll make that change and incorporate into the next release.

Thanks for the bug report!!

**Comment by mlesin** [comment]
Thanks for a quick response, now it works without exceptions!
By the way, Socket.destroy() is not asynchronous, so it doesn't need await. I'm not sure it's really important, probably it's more about cleaning a code, because it's working with and without it :)
