### ISSUE TITLE
Feature request: StartTLS support

### ISSUE THREAD

**Issue by ghenry** [wstrange/dartdap#23]
Hi,

It would be great to add:

https://tools.ietf.org/html/rfc4511#section-4.14
https://tools.ietf.org/html/rfc4513

Thanks.

**Comment by philippderdiedas** [comment]
project abadoned?

**Comment by wstrange** [comment]
It's always been a project I've done in my spare time. PRs welcome ;-)

**Comment by wstrange** [comment]
Note you can use LDAPS (Ldap over TLS ) - but start tls has not been implemented. I'm actually not sure how to implement the upgrade to tls over Dart sockets.  If someone wants to have a go at this, I'd welcome it

This is a good reference: https://fy.blackhats.net.au/blog/html/2021/08/12/starttls_in_ldap.html

And this thread on start tls vs. ldaps: 

https://lists.openldap.org/hyperkitty/list/openldap-technical@openldap.org/thread/IXEZAGCOTL5CTSOFNFDE65LURQET6ZZV/#LZ4N3JHGKZVDXRIXNRAM4SHZ44B5U4BP
