### ISSUE TITLE
Lisp interpreter - feature

### ISSUE THREAD

**Issue by supermuka** [wstrange/dartdap#24]
Would be nice if we could to create a Filter based on Lisp.

**Scenario**:

Convert from  _Lisp Filter_:

`(&(objectClass=posixGroup)(cn=group))`

To _Dart Filter_  with `dartdap`  package:

`Filter groupFilter = Filter.and(List<Filter>()..add(Filter.equals("objectClass", "posixGroup"))..add(Filter.equals("cn", "group")));`

The idea is just inform a Lisp statement and a `Filter` instance would be created based on. This could be implemented with a namely constructor like a `Filter.fromLisp((&(objectClass=posixGroup)(cn=group)))`

**Comment by wstrange** [comment]
Interesting idea. Are you suggesting those would be constructed using operator overloading? 


I think what we should probably implement would be some kind of Filter constructor that uses https://tools.ietf.org/html/rfc2254  syntax.   

`Filter.fromQueryString("(&(objectClass=posixGroup)(cn=group))")`



See https://pub.dev/packages/petitparser#-readme-tab-

**Comment by chrisridd** [comment]
The RFC syntax is definitely the one to choose. However although it is very VERY convenient, it is also a perfect way to add LDAP injection attacks into an application so there definitely need to be additional safe ways to build filters.

**Comment by wstrange** [comment]
@chrisridd Would that consist of sanitizing / escaping the arguments? So something like:

`Filter.fromQueryString("(&(objectClass=posixGroup)(cn=$1))", args: [ "group" ] )`

Assuming the args array is escaped / sanitized

**Comment by supermuka** [comment]
Yes @wstrange, a named constructor I think it would be a way... And your considerations are pretty accurate and important.

**Comment by chrisridd** [comment]
That looks good, Warren.

**Comment by wstrange** [comment]
Closed via #25

Beta status until it has more testing.

**Comment by wstrange** [comment]
Note: This *DOES NOT* support escaping of the filter to sanitize the input.

It also needs more love on the parser. It does not support special characters (ascii only filters), caching of queries. etc.
