### ISSUE TITLE
Filter toString() method printing null elements 

### ISSUE THREAD

**Issue by supermuka** [wstrange/dartdap#28]
_dartdap version 0.4.2_

`Filter` list is printing `null` elements that don't defined. 

**code:**
```
void main() {
  var userSearchFilterDartdap =  dartdap.Filter.and([dartdap.Filter.equals('objectClass', 'posixAccount'),dartdap.Filter.equals('dn', 'cn=MI,ou=users,dc=auge,dc=levius,dc=com,dc=br')]);
  print(userSearchFilterDartdap);
}
```

**print:**

> Filter(type=0xa0 attrName=null val=null, subFilters=[Filter(type=0xa3 attrName=objectClass val=posixAccount, subFilters=null), Filter(type=0xa3 attrName=dn val=cn=MI,ou=users,dc=auge,
> dc=levius,dc=com,dc=br, subFilters=null)])

Null elements that _should not exist_:
On `type=0xa0` `attrName=null val=null`
On `type=0xa3` `subFilters=null`
On `type=0xa3` `subFilters=null`

**expected something like:**

> Filter(type=0xa0, subFilters=[Filter(type=0xa3 attrName=objectClass val=posixAccount), Filter(type=0xa3 attrName=dn val=cn=MI,ou=users,dc=auge,
> dc=levius,dc=com,dc=br)])

**Comment by wstrange** [comment]
Just to clarify - this looks like a problem with the `toString` method, right? 
Does the ldap server complain when you try and send that search request?

**Comment by supermuka** [comment]
Yes, I think that is a problem of the implementation in the `toString` method. The search request on server, _a priori_, is working.
