### ISSUE TITLE
Unhandled exception: Size limit exceeded

### ISSUE THREAD

**Issue by insinfo** [wstrange/dartdap#29]
I am trying to re-implement in Angel dart a backend of a web application that builds with PHP and Slim Framework together with authentication integrated with Microsoft Active Directory. I'm trying to use lib dartdap 0.4.3 to do the authentication part with Active Directory, in addition to the authentication part I also need to list Active Directory users in a paginated way in a DataTable in AngularDart,
I'm getting the Size limit exceeded exception. How to proceed so that you can list users in a paginated way

##### DART code 
```dart
const host = "192.168.133.10";
const bool ssl = false; 
int port; 
var bindDN = 'CN=Usuario Desenvolvimento Sistemas,CN=Users,DC=dcro,DC=gov'; 
var domainAdminPassword = '@#Ins257257pmr0'; 
var ldapDomain = 'DC=dcro,DC=gov';
var ldapUserDomain = '@dcro.gov';
var user = 'desenvolvimento';
var ldaprdn = user + ldapUserDomain;
final connection = LdapConnection(host: host);
connection.setProtocol(ssl, port); 
var result = await connection.setAuthentication(bindDN, domainAdminPassword);  
var base = "$ldapDomain";
var filter = Filter.present("sAMAccountName");   
var attrs = ["dc", "objectClass","cn","sAMAccountName"];
var count = 0;
var searchResult = await connection.search(base, filter, attrs);
    searchResult.stream.listen((onData){
     print(" ${onData}");
});

```

I also have another question regarding the authentication of a user, because in PHP and I use the function ldap_bind (ldap_connect ('host'), 'login@domain.com', 'password') to authenticate a user but in dartdap I don't I know how to proceed, because I didn't find an ldap_bind method that receives "sAMAccountName@domain.com" as an argument to authenticate the user.

##### PHP code example
```php
$ldapConnection = ldap_connect('ldap://192.168.133.10');
$ldapUserDomain = '@dcro.gov';
$ldaprdn = $user . $ldapUserDomain;
//Returns TRUE on success or FALSE on failure.
if(ldap_bind($ldapConnection, $ldaprdn, $password)){
//user logged in
}else{
//Non-existent user, without permission or invalid password
}
```

**Comment by wstrange** [comment]
Your first query is asking AD to return every single user in the directory, which can be a very large query. The directory is telling you to narrow the query to return less data.

 Can you modify your query to be much more specific, or do you *really* need every single user returned? Typically for user authentication / authorization, you will query for the specific user.

**Comment by wstrange** [comment]
For the second question, I am *not* an AD expert, but you probably want to search for the user first (search for user with that samaccountname). That search will give you the DN of that user.
You then take the DN, and use that (along with the users password) to BIND to the directory. If the BIND succeeds, you know the user can authenticate with that password.

**Comment by wstrange** [comment]
For pagination, the `query` method takes an optional list of LDAP controls.  There is a [VLV Control ](https://ldapwiki.com/wiki/Virtual%20List%20View%20Control)
that can be used to return sorted and paginated results.  So you would do something like

```
searchResult = await ldap.query(baseDN,query,attrs, controls: [VLVrequestControl.offsetControl(...)])

searchResult.controls - returns a list of controls - which may include a VLV response telling you the remaining results, where to start the next query, etc.
```

Note the *server* must support VLV controls (this is not just an ldap client control).

**Comment by wstrange** [comment]
Related: #30

**Comment by insinfo** [comment]
Hello, thanks for the quick feedback, I changed the MaxPageSize of the Microsft Active Directory Server using ntdsutile Set MaxPageSize to 7000 following this Tutorial:
https://support2.microsoft.com/en-us/help/315071/how-to-view-and-set-ldap-policy-in-active-directory-by-using-ntdsutil

but changing the MaxPageSize is a temporary solution because if I increase the number of entries I will have a problem again, so I tried to implement the solution you proposed, but I'm always getting 6280 results instead of just 10, the code is below, I will be doing something wrong or is it a bug?

```dart
//first execution params
    int offset = 1;
    int contentCount = 10;
    int beforeCount =0;
    int afterCount =10;
    List<int> contextId = [10];

     String query = "(&(objectClass=user)(objectCategory=person)(sn=*))";
    var searchResult = await connection.query(
      base,
      query,
      attrs,
      controls: [VLVRequestControl.offsetControl(offset, contentCount, beforeCount, afterCount, contextId)],
    );

    await for (var entry in searchResult.stream) {
      print("count: ${count}");
      count++;
    }

```
Microsoft Active Directory supports VLV
https://docs.microsoft.com/en-us/windows/win32/adsi/how-to-search-using-vlv

my PHP implementation example

```php
 /**    
     * get all users of AD  for list in DataTable
     * @return array
     */
    public function getAllUser()
    {      
        $conn = $this->ldapConnection;
        $base = $this->ldapDomain;
        //$filter="(cn=*)";
        //$filter="(sAMAccountName=*)";
        $filter = "(&(objectClass=user)(objectCategory=person)(sn=*))";
        $justthese = array();
        $pageSize = 300;
        $cookie = '';
        $count = 0;
        $data = array();
        do
        {
            ldap_control_paged_result($conn, $pageSize, true, $cookie);

            $result = ldap_search($conn, $base, $filter, $justthese);
            $entries = ldap_get_entries($conn, $result);

            if (!empty($entries))
            {
                for ($i = 0; $i < $entries["count"]; $i++)
                {
                    $data[] = array('name' => $entries[$i]["cn"][0], 'username' => $entries[$i]["samaccountname"][0]);
                    $count++;
                }
            }
            ldap_control_paged_result_response($conn, $result, $cookie);

        }
        while ($cookie !== null && $cookie != '');
        array_multisort($data);//ordena o array alfabeticamente
        return $data;
    }

     public function getAllUserByLimit($currentPage = 1, $recordsPerPage = 50)
    {
        if ($this->ldapConnection == null && $this->authenticatedUser == null)
        {
            new Exception('Autentique primeiro!', 400);
        }
        $lista = array();

        $entries = $this->getAllUser();
        $entriesCount = count($entries);

        if ($currentPage < 0)
        {
            $currentPage = 0;
        }
        if ($currentPage == 0)
        {
            $currentPage = $currentPage + 1;
        }
        $totalRecords = $entriesCount;
        $totalNumberOfPages = ceil($totalRecords / $recordsPerPage);
        // calculando início e fim da seleção
        $qtdrow = $recordsPerPage;
        $pagfim = ($currentPage * $qtdrow);//72*10 =720
        $pagini = ($pagfim - $qtdrow) + 1;//720-10+1=711

        if ($currentPage > $totalNumberOfPages)
        {
            return null;
        }

        for ($i = $pagini - 1; $i < $pagfim; $i++)
        {
            if ($i == $totalRecords)
            {
                break;
            }
            $item = array();
            $item['nome'] = $entries[$i]['name'];
            $item['login'] = $entries[$i]['username'];
            array_push($lista, $item);
        }
        return $lista;
    }
```

**Comment by insinfo** [comment]
Regarding user authentication in LDAP, I find it very strange that I have to authenticate with the Active Directory administrator user, search for the user in AD, obtain the DN of this user and then authenticate again with this DN, it is strange because both OpenLDAP when Microsoft Active Directory already has an authentication function called ldap_sasl_bind_s () or ldap_simple_bind_s () that receives the connection instance and the 'login@domain.com' and password


https://linux.die.net/man/3/ldap_sasl_bind_s
https://docs.microsoft.com/en-us/windows/win32/api/winldap/nf-winldap-ldap_simple_bind_s
https://docs.microsoft.com/en-us/windows/win32/api/winldap/nf-winldap-ldap_sasl_bind_sa
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/apis/ldap_sasl_bind_s.htm
https://github.com/php/php-src/blob/master/ext/ldap/ldap.c
https://github.com/openldap/openldap/blob/master/include/ldap.h

Shouldn't the lib dartdap exhibit an ldapSimpleBind () method as well as the C and PHP implementations?

**Comment by insinfo** [comment]
Another problem I saw, I don't know if it really is a problem anymore, where I pass the LDAP client certificate path, in PHP I just need to put the Certficado in the folder "C:\OpenLDAP\sysconf\certdcro.cer" or no Linux in "/etc/ldap/ldap.conf" I add a line with the path "TLS_CACERT /var/www/html/config/certdcro.cer"

I don't know if it really is a problem because apparently I'm getting access and listing entries with SSL enabled, but I haven't tested yet if I can add entries and change user passwords without the certificate, I remember if I'm not wrong in PHP at the time I implemented it I couldn't do certain operations without the certificate save mistake

**Comment by wstrange** [comment]
On the VLV question, I suspect the offset and afterCount should be 0. Note that you must read the VLV control that you get back in the search request, and use the data it returns to issue the next query. This will get the next "page" of results.

**Comment by wstrange** [comment]
W.r.t. the ldap bind, yes it would probably be a nice addition to have a simple bind call. 

What I would suggest is creating two connections. Keep one connection open as the AD admin, and then use another connection for binding as the user.

**Comment by wstrange** [comment]
On the AD certificate question: I am not an AD expert, but I believe if you are connecting to AD via SSL, it will allow you to perform priviliged operations.

**Comment by chrisridd** [comment]
> On 3 Mar 2020, at 16:04, insinfo <notifications@github.com> wrote:
> 
> Regarding user authentication in LDAP, I find it very strange that I have to authenticate with the Active Directory administrator user, search for the user in AD, obtain the DN of this user and then authenticate again with this DN, it is strange because both OpenLDAP when Microsoft Active Directory already has an authentication function called ldap_sasl_bind_s () or ldap_simple_bind_s () that receives the connection instance and the 'login@domain.com' and password

ldap_simple_bind_s is what dartdap already implements, ie bind with a *DN* and a password. That’s the LDAP standard.

ldap_sasl_bind_s would require that dartdap supported SASL, but that would typically let you bind with a non-DN like john@example.com and a password.

Note that supporting SASL will be a pain when Microsoft tightens up AD security restrictions on SASL, ie you have to support mechanisms with integrity layers. This tightening up is happening next week, as it happens: https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows

Are you sure you need to bind as an AD admin to do your search? Try anonymously.

Cheers,

Chris

**Comment by insinfo** [comment]
@chrisridd 
From what I read the update that Microsoft released does not break ldap_simple connections, it only provides one more security option that is not enabled by default. This update provides the option to reject non-SSL connections and or the option to require validation of LDAP signing. From what I read once this security option was enabled, non-SSL connections stop working. But what I mentioned is the use of ldap_simple_bind_s with SSL (I use TLS CA Cert in PHP) because it remains secure because the data travels encrypted over the network. Anyway, I talked to the domain administrators of the companies that I provide services and they were all resistant to implement these restrictions since they have many applications that would stop working, like proxy servers, ownCloud servers, gitlab servers, onlyoffice, zimbra among others. I don't think ldap_simple will die.
ldap_simple over TLS would be a good authentication option for dartdap



> Clients that rely on unsigned SASL (Negotiate, Kerberos, NTLM, or Digest) LDAP binds or on LDAP simple binds over a non-SSL/TLS connection stop working after you make this configuration change. 
Source: https://support.microsoft.com/en-us/help/935834/how-to-enable-ldap-signing-in-windows-server-2008

> Anonymous LDAP operations for active directory are disabled on Windows domain controllers
Source: https://support.microsoft.com/pt-br/help/326690/anonymous-ldap-operations-to-active-directory-are-disabled-on-windows

Interesting: https://www.reddit.com/r/sysadmin/comments/eril29/can_someone_explain_what_ldap_channel_binding_is/

**Comment by insinfo** [comment]
@wstrange 

> On the VLV question, I suspect the offset and afterCount should be 0. Note that you must read the VLV control that you get back in the search request, and use the data it returns to issue the next query. This will get the next "page" of results.

my code for test
```dart
  //configurations of conection
    const host = "192.168.133.10";
    const bindDNdomainAdmin = 'CN=Usuario Desenvolvimento Sistemas,CN=Users,DC=dcro,DC=gov'; // null=unauthenticated
    const domainAdminPassword = '@#Ins257257pmr0'; //@#Ins257257pmr0
    //active directory domain name DN (base location of ldap search) ex "OU=Departments,DC=college,DC=school,DC=edu"
    const ldapDomain = 'DC=dcro,DC=gov';
    const base = "$ldapDomain";
    const ldapUserDomain = '@dcro.gov';
    var user = 'desenvolvimento';
    var ldaprdn = user + ldapUserDomain;
    const bool ssl = true; // true = use LDAPS (i.e. LDAP over SSL/TLS)  
    const int port = 636; // null = use standard LDAP/LDAPS port
    final connection = LdapConnection(
        host: host,
        ssl: ssl,
        port: port,
         bindDN: bindDNdomainAdmin,
         password: domainAdminPassword,
        badCertificateHandler: (X509Certificate cert) {
          return true;
        }); 

    final attrs = ["distinguishedName", "dn", "objectClass", "cn", "sAMAccountName"];
    var count = 0;    
    //first execution params
    int offset = 0;
    int contentCount = 10;
    int beforeCount = 10;
    int afterCount = 0;
    List<int> contextId = [10];
    String query = "(&(objectClass=user)(objectCategory=person)(sn=*))";
    var searchResult = await connection.query(
      base,
      query,
      attrs,
      controls: [VLVRequestControl.offsetControl(offset, contentCount, beforeCount, afterCount, contextId)],
    );
    print('controls ${searchResult.controls}');
    await for (var entry in searchResult.stream) {
      print('entry $count');
      count++;
    }
```
searchResult.controls is null and searchResult.stream keeps bringing all items, even setting offset = 0; contentCount = 10; beforeCount = 10; afterCount = 0;

![image](https://user-images.githubusercontent.com/12227024/75824060-a0504180-5d81-11ea-8541-6b62f384311f.png)

**Comment by wstrange** [comment]
@insinfo I just commited a new sample https://github.com/wstrange/dartdap/blob/master/example/paged_search.dart 

(update pub version to 0.4.4)

This uses  Simple Paged Search to fetch one page at a time. I am not 100% sure that AD supports this control - but please give it a try. When I get more time I will see if I can look at the VLV search.

**Comment by wstrange** [comment]
@insinfo Did you have a chance to try out that paged search example? I'll close this issue for now - feel free to open a new issue if you run into problems.
