### ISSUE TITLE
Unsupported operation : Socket constructor error on Flutter Web

### ISSUE THREAD

**Issue by burakcet** [wstrange/dartdap#33]

**Comment by wstrange** [comment]
LDAP is not going to work in the browser (Flutter Web) - this is a server side library.  Closing for now.

**Comment by burakcet** [comment]
Hi,

I am trying to connect our ldap server and trying to get success result of
authentication correction( valid credentials ). I mentioned below, I got an
error  Unsupported operation : Socket constructor
<https://github.com/wstrange/dartdap/issues/33>
It works on mobile correctly. Is there a way to use it on Web? It's
important for me.

 var host = "***";
           var ssl = false;
           var port = null;
           var bindDN = "ttf\\${_username}";
           var password = _password;

           var connection = new LdapConnection(host: host);
           connection.setProtocol(ssl, port);
           connection.setAuthentication(bindDN, password);

var searchResult = await connection.open(); <---- This part i got that
error on Flutter Web application.

**Comment by wstrange** [comment]
No, LDAP will not work in a web browser (in any web framework - this is not a Dart / Flutter thing..)

If you are using ForgeRock DS, it has a rest2ldap endpoint that can translate ldap to HTTP calls.
