### ISSUE TITLE
Set a timeout value in LdapConnection

### ISSUE THREAD

**Issue by sfm1977** [wstrange/dartdap#43]
Hi,

Is it possible to set a timeout value in connection? If the connection is down, it takes forever to stop trying.

Thanks,

**Comment by wstrange** [comment]
Yea - I think we could add a timeout Duration to the socket.connect() call. 
I'll see if I can get to this on the weekend

**Comment by wstrange** [comment]
I just pushed 0.6.1 that sets a 30 second timeout on the socket.connect().

Can you LMK if it fixes the issue.  Thx

**Comment by sfm1977** [comment]
I was referring to give a time out option on LdapConnection, something like this:

```
  var _conn = LdapConnection(
      host: _host,
      ssl: true,
      port: 636,
      badCertificateHandler: (X509Certificate cert) => true,
      timeoutInSeconds: 3,
    );`
```

**Comment by wstrange** [comment]
If there is a compelling need for a programmable timeout, please create a PR.
