### ISSUE TITLE
LDAP login in Flutter web is not working

### ISSUE THREAD

**Issue by Tapasm1212** [wstrange/dartdap#45]
I am trying to bind and search users in LDAP using this package but in flutter web, it's not working. Do you guys please suggest to me how can I do that in the flutter web application?

**Comment by wstrange** [comment]
Flutter web runs in the browser, and browsers can not create LDAP connections.  You must find another way of doing this.

For example you could do something like

flutter web app --> dart server + dartdap --> LDAP
