### ISSUE TITLE
ModifyDN doesn't move to new superior

### ISSUE THREAD

**Issue by generalovserg** [wstrange/dartdap#48]
It's possible to change RDN, but not working for newSuperior.
Tested with AD.

**Comment by wstrange** [comment]
I'm not sure if newSuperior has ever been tested - so it's possibly not working.  The class in question is moddn_request.dart if you want to take a look.  Possibly the _newSuperior is not getting added properly?  What does the AD server indicate?

**Comment by generalovserg** [comment]
In moddn_request.dart newSuperiorDN is adding to request:

```
@override
  ASN1Object toASN1() {
    var seq = _startSequence();
    seq.add(ASN1OctetString(_dn));
    seq.add(ASN1OctetString(_newRDN));
    seq.add(ASN1Boolean(_deleteOldRDN));
    if (_newSuperiorDN != null) seq.add(ASN1OctetString(_newSuperiorDN));
    return seq;
  }

```

In AD log:
- Internal event: A privileged operation (rights required = 0x) was successfully performed on object CN=Test Test,OU=ou2,OU=ou1,DC=idm,DC=local.
- Internal event: Function ldap_modDN entered.
       SID: S-1-5-21-759978434-2663428554-911949384-1103
       Source IP: 10.1.1.18:54023
       Operation identifier: 10600
       Data1: 
       Data2: 324592656
       Data3: 
       Data4: 

The invoking code is trivial:   
```
 var conn = await pool!.getConnection(bind: true);
    var result = await conn.modifyDN(
      utf8str('CN=Test Test,OU=ou2,OU=ou1,DC=idm,DC=local'),
      utf8str('CN=Test Test'),
      newSuperior: utf8str('OU=ou1,DC=idm,DC=local'),
    );
```

**Comment by chrisridd** [comment]
In the RFC, the tag for newSuperior is overridden and is not OCTET STRING.

        ModifyDNRequest ::= [APPLICATION 12] SEQUENCE {
             entry           LDAPDN,
             newrdn          RelativeLDAPDN,
             deleteoldrdn    BOOLEAN,
             newSuperior     [0] LDAPDN OPTIONAL }

This is why AD is rejecting the badly encoded operation. OpenLDAP will likely do the same, so you could probably test against OpenLDAP if you don't have AD. Servers that don't do lots of tag checking will miss this error.

**Comment by chrisridd** [comment]
@generalovserg try tweaking the line adding newSuperior to this:

    if (_newSuperiorDN != null) seq.add(ASN1OctetString(_newSuperiorDN, tag: 0x80));

You may need to fiddle with the dart syntax a bit to get it to compile, but you can hopefully see the intent.

**Comment by generalovserg** [comment]
Yes! That helped! 
Thank you very much!
Hope you include this fix in next version.

**Comment by wstrange** [comment]
Chris - thanks for the clue!

I'll try to get out a new version for this in next couple of days.

**Comment by chrisridd** [comment]
FWIW after a quick and dirty grep I couldn't see any other current cases where the tag needs to be overridden but isn't.

**Comment by wstrange** [comment]
@generalovserg I pushed v0.6.3 with this fix.
