### ISSUE TITLE
Search request freezes

### ISSUE THREAD

**Issue by generalovserg** [wstrange/dartdap#49]
Sometimes the search returns instantly, but without a result.
Waiting for ldapresult is infinite.
It's for AD.

**Comment by wstrange** [comment]
Unfortunately I don't have access to AD - so you will need to help me out with more debugging information.  Turn up the logs to trace level.  

Info from the AD side is also going to be helpful.  Is the AD server finished with the request, does it complain of errors, etc.

If you can provide a code snippet I can take a quick look as well.

**Comment by wstrange** [comment]
@generalovserg Any updates?

**Comment by generalovserg** [comment]
Make loop of

```
        var result = await conn.search('CN=Users,DC=idm,DC=local',
            Filter.equals('objectCategory', 'group'), ['cn']);

        await for (var entry in result.stream) {
          log.info(entry.dn);
        }

```

After some number of iterations it hangs and no entry returned.

Last entries in log:
2022-06-28 10:29:03.936915: ldap.connection: FINE: search
2022-06-28 10:29:03.937911: ldap.send.ldap: FINE: [31] Sending LDAP message: Msg(id=31, op=SRCH_REQ,controls=Seq[])
2022-06-28 10:29:03.937911: ldap.send.bytes: FINEST: [31] Bytes sending: [48, 77, 2, 1, 31, 99, 72, 4, 24, 67, 78, 61, 85, 115, 101, 114, 115, 44, 68, 67, 61, 105, 100, 109, 44, 68, 67, 61, 108, 111, 99, 97, 108, 10, 1, 2, 10, 1, 0, 2, 1, 0, 2, 1, 0, 1, 1, 0, 163, 23, 4, 14, 111, 98, 106, 101, 99, 116, 67, 97, 116, 101, 103, 111, 114, 121, 4, 5, 103, 114, 111, 117, 112, 48, 4, 4, 2, 99, 110]

Looks like there is no received bytes.

As workaround i do this:
```
while (retry) {
      try {
        result = await conn.search(baseDN, filter, attributes,
            scope: scope, sizeLimit: sizeLimit);
        await Future.value(result.getLdapResult())
            .timeout(Duration(seconds: 2));
        retry = false;
      } on TimeoutException {
        log.warning('Search timeout');
        retry = n++ < 3;
      }
    }
```
Cant see anything usefull on the AD side.

Thank you.

**Comment by chrisridd** [comment]
The bytes sent look correct, on first inspection. Are you flooding AD with too many operations too quickly?

**Comment by wstrange** [comment]
Some other thoughts/questions/things to try:

- How many results do you expect? Are there a lots of groups? More than would exceed the size limit of the server? 
- What happens if you limit the search result size. Try 10 or so. Does it make it make the  search results stable?
- Are there any other open connections / futures at the same time as the search that freezes?
- After the "Sending LDAP message: Msg(id=31," Is there any ldap diagnostic message at all, or does it just hang?
- If it hangs, you might try to run this with the debugger, and see where it hanging...

**Comment by wstrange** [comment]
@generalovserg any updates?
