### ISSUE TITLE
While creating a user in AD using LDAP 

### ISSUE THREAD

**Issue by avinash-gotluru** [wstrange/dartdap#54]
what is the attribute do we have to use to enable the User 

` var attrs = {
      "objectClass": ["top", "person", "organizationalPerson", "user"],
      "givenname": "John",
      "sn": "G",
      "uid": "John1",
      "userPassword": "QXZpbmFzaCQ5NTMz",
      "mail": "Johng@skk.com",
      "UserAccountControl": "512",
      "telephoneNumber": "+91 999999999"
    };`
    
  I'm using the above code.
  could you please let me know how to enable the user using the LDAP

**Comment by wstrange** [comment]
I dont use AD, so I'm not much help here. 

I think you are on the right track with the userAccountControl attribute.  You are setting a string value there and not an integer ( "512"). That might cause issues - not sure. Have a look at the error code from AD (from the dart side, but also from the AD logs).  Compare the user that is created with one created via the AD console.   Or create a user in AD, then fetch the userAccountControl attribute to see what it looks like coming back from AD.

**Comment by wstrange** [comment]
Closing this for now, as I dont think its a bug in dartdap.  Please reopen if you have more data.
