### ISSUE TITLE
'ASN1Application' is not a subtype of type 'ASN1Sequence'

### ISSUE THREAD

**Issue by Coimbra1984** [wstrange/dartdap#55]
Hi,

I try to perform an LDAP bind:

```
  var connection = LdapConnection(
    host: xxx,
    bindDN: xxx,
    password: xxx,
    ssl: true,
    port: 636,
    badCertificateHandler: (X509Certificate cert) {
      print("BAD certificate!!!");
      return true;
    },
  );

  try {
    print("connection.open()");
    await connection.open();
    print("...ok");

    var res = await connection.bind();
    print(res.toString());
  } on Exception catch (e) {
    print("error: ${e.toString()}");
  }
```

This fails unfortunately here:
[    _protocolOp = elements[1] as ASN1Sequence;](https://github.com/wstrange/dartdap/blob/40eb55a31b9500acdb48b066722ca64ffe7ae5ea/lib/src/dartdap/protocol/ldap_message.dart#L95)

because elements[1] is of type ASN1Application:

My Debugger gives the following details on elements[1] if this helps:

```
[1]:
ASN1Application (ASN1Object(tag=61 valueByteLength=7) startpos=2 bytes=[0x61, 0x7, 0xa, 0x1, 0x0, 0x4, 0x0, 0x4, 0x0])
_encodedBytes:
_Uint8ArrayView ([97, 7, 10, 1, 0, 4, 0, 4, 0])
_tag:
97
_valueByteLength:
7
_valueStartPosition:
2
encodedBytes:
_Uint8ArrayView ([97, 7, 10, 1, 0, 4, 0, 4, 0])
hashCode:
2365126261
isEncoded:
true
runtimeType:
Type (ASN1Application)
tag:
97
totalEncodedByteLength:
9

```

**Comment by wstrange** [comment]
Can you tell me what version your asn1 library is in your pubspec. Thanks

**Comment by wstrange** [comment]
If you can roll back to a previous version of the asn1 library (1.2.0), I think this will work around the issue. 

I think I know the problem and will take a look later today.

**Comment by Coimbra1984** [comment]
Thanks for the reply. I changed to asn1 library 1.2.0, unfortunately I still get an error. Now elements[1] is of type ASN1Object. The error message is type 'ASN1Object' is not a subtype of type 'ASN1Sequence' in type cast

```
[1]:
ASN1Object (ASN1Object(tag=61 valueByteLength=7) startpos=2 bytes=[0x61, 0x7, 0xa, 0x1, 0x0, 0x4, 0x0, 0x4, 0x0])
_encodedBytes:
_Uint8ArrayView ([97, 7, 10, 1, 0, 4, 0, 4, 0])
_tag:
97
_valueByteLength:
7
_valueStartPosition:
2
encodedBytes:
_Uint8ArrayView ([97, 7, 10, 1, 0, 4, 0, 4, 0])
hashCode:
1455840722
isEncoded:
true
runtimeType:
Type (ASN1Object)
tag:
97
totalEncodedByteLength:
9
```

**Comment by wstrange** [comment]
I think I know what the issue is with the current version of asn1, but that older version should not have the issue. Are you sure you dont have a cached asn1 library version?

**Comment by wstrange** [comment]
Pin the asn1 to 1.0.3 for now... 

Thanks for your patience

**Comment by wstrange** [comment]
I just pushed dartdap 0.6.4 that temporarily pins the asn1 library.

**Comment by Coimbra1984** [comment]
Okay, cool. I can confirm, that using asn1 1.0.3 works!

I did a `flutter clean` and `flutter pub get` and tested once again with asn1 1.2.0 but this doesn't work here (I'm building a windows app).

Anyway 1.0.3 works!

**Comment by Coimbra1984** [comment]
I can confirm that dartdap 0.6.4 fixes my issue. Thanks

**Comment by wstrange** [comment]
Just pushed 0.6.5, which uses the updated asn1 library.
