### ISSUE TITLE
Exception Control 2.16.840.1.113730.3.4.5 not implemented

### ISSUE THREAD

**Issue by Pingoo31** [wstrange/dartdap#56]
Hi,

When using the dartdap module in a production application, we encounter an error that only occurs when the user is notified that their password is going to expire (in 30 days).
We see in the application logs an unimplemented exception on the Control **2.16.840.1.113730.3.4.5** **Password Expiration Warning Control**.
This bug is blocking because the user can no longer log in even though their password is still valid.

**Comment by wstrange** [comment]
I'm guessing the dartdap client doesn't like the control being sent back from the server. It's a control that has not been implemented yet in the client.

To get around this problem in the (very) short term, your server probably has some way of clearing that control field so the server doesn't send it to the client. You would have to do that manually as an admin.

It would be helpful if you can get a trace in the client of the sequence that triggers this. I can try to take a look at this later this week.

**Comment by wstrange** [comment]
Also - a more complete error log would help

**Comment by Pingoo31** [comment]
We work with a directory in production for several thousand users and cannot modify it in any way.
From my point of view, classes that implement LDAP in other languages pose no problem, this is the first time we have had this type of problem.

moreover, I think it is important to warn the user that their password will expire...

I  send the log as soon as possible.

**Comment by chrisridd** [comment]
Really, dartdap should not be throwing any sort of exception if it gets an unknown control.

If logging the control's OID somewhere is possible before just continuing, that would IMO be the best option.

BTW that control is defined in https://datatracker.ietf.org/doc/html/draft-vchu-ldap-pwd-policy

**Comment by wstrange** [comment]
Yep - agreed.  This in the `_parseControl` method. It throws an exception if it doesn't recognize the control.

I'll create a fix to just log the unknown control.

**Comment by wstrange** [comment]
Pushed 0.7.0 to pub.dev

**Comment by Pingoo31** [comment]
Good morning,

Many thanks for the responsiveness and correction of this bug.
We will test this fix quickly and I will come back to comment on the evolution ;-)

Here is the log of the error that blocked us:
![dartdap_error](https://github.com/wstrange/dartdap/assets/43337711/29eb19cd-d22b-4e12-8d00-397f9c609a16)
