### ISSUE TITLE
LDAP paged search gives an ASN1 exception

### ISSUE THREAD

**Issue by bothw** [wstrange/dartdap#58]
I'm using the default paged search example and I get an exception from the ASN1 when a new ASN1 object is created.

The error message is : "The tag 16 does not look like a sequence type"

Raised on new ASN1Sequence.fromBytes (c:\Users\Admin\AppData\Local\Pub\Cache\hosted\pub.dev\asn1lib-1.5.2\lib\src\asn1sequence.dart:20)

I'm using the latest versions dartdap 0.7.0 and asn1lib 1.5.2

The only way to get this working is to downgrade to dartdap 0.6.3 with ans1lib 1.1.1 and it is working fine.
The problem with that it gets conflicts with other libraries when I want to write a more complex program where this part of.

**Comment by wstrange** [comment]
Hm - I made some changes to asn1 version 1.5.2.

Are you able to do a quick test for me?   Use dartdap 0.7.0 but pin asn1 to 1.5.0.   

That would help to isolate the problem.

**Comment by wstrange** [comment]
OK - NVM, the asn1 lib is not the issue. I think I found the problem.

Can you try version 0.7.1 that I just pushed to pub

**Comment by bothw** [comment]
Hi, thanks for your quick response. The version 0.7.1 works fine.
