### ISSUE TITLE
Search filter with parentheses

### ISSUE THREAD

**Issue by Coimbra1984** [wstrange/dartdap#62]
Hi,

it's me again. Having solved issue https://github.com/wstrange/dartdap/issues/60 brought me one step further. The next problem is now at our customer. He has parentheses in his CNs.

I have set up a similar example with openLDAP:
`cn=Test\2C Testuser (man),ou=people,dc=pieye,dc=org`
If I try to use this with the query function, I get again a parse filter error:
`flutter: Cant parse filter '(roleOccupant=cn=Test\5C2C Testuser (man),ou=people,dc=pieye,dc=org)'. Error is ")" expected`

Best regards

**Comment by wstrange** [comment]
From my read of https://ldap.com/ldap-filters/ , I think parentheses must be escaped:

- Any occurrence of the open parenthesis character must be escaped as “\28”.
- Any occurrence of the close parenthesis character must be escaped as “\29”.

That being said, I'm not sure that works. Can you test and let me know

**Comment by Coimbra1984** [comment]
okay, did not get this point. It works with escaping as suggested.
