### ISSUE TITLE
Search filter with underscore

### ISSUE THREAD

**Issue by Coimbra1984** [wstrange/dartdap#63]
Hi,

as mentioned here: https://github.com/wstrange/dartdap/issues/62#issuecomment-2329767445 the LDAP filters must comply with the specification. I did not read there, that underscores must be escaped.
When I try the following DN, I get an error:
```
CN=AL10admin,OU=Test_Qualification_Notfall,OU=Users,OU=Production,DC=atlnz,DC=prod
flutter: Cant parse filter '(roleOccupant=CN=AL10admin,OU=Test_Qualification_Notfall,OU=Users,OU=Production,DC=atlnz,DC=prod)'. Error is ")" expected

```

When I remove the underscore, it works fine.

Best regards

**Comment by wstrange** [comment]
I added the underscore to the attribute list. Give it a try and LMK (0.7.4)

**Comment by Coimbra1984** [comment]
Look good, thanks
