### ISSUE TITLE
Parsing of search result ASN.1 objects

### ISSUE THREAD

**Issue by hoylen** [wstrange/dartdap#8]
Warren,

Thanks for merging in my implementation of the _StreamTransformer_ that converts bytes into _LDAPMessages_. The previous implementation assumed all the bytes of an entire ASN.1 object was available when the _handleData_ method was called, but there is no guarantee that would be the case. In particularly, that was not true when I tried to connect to a TLS/SSL secured OpenLDAP server (the _handleData_ method got called with the very first byte, and then called again later with the rest of the object).

What do you think about these things to be done:
1. I'm finding that LDAP search operations are quite unreliable, usually resulting in the application hanging. I think certain ASN.1 objects returned by a search are not being parsed/handled. This requires some low level work at the byte-level; possibly fixes in _asn1lib_ too. Having said that, I've found the other operations (e.g. create, delete and modify) to work without problems so far.
2. Relating to item 1, if there are more results than the requested limit an exception is still thrown. I'm thinking that, if you asked for a maximum of 5 results and you got 5 back (even though there is more available in the directory) the search operation should not throw an exception.
3. For testing, we should define what entries are expected in the LDAP directory. Is there a desire to keep the existing tests working, or can we change them to work with a well defined test directory? I'm thinking of putting together instructions for a base-line deployment of OpenLDAP (which people can create easily in a virtual machine running CentOS) and making sure the integration tests work with that. Then we have a repeatable environment to start tackling item 1.
4. They claim the Dart formatter (_dartfmt_ or ⌘-Shift-R in the Dart Editor) is better. Shall we run it on all the code to get them all into a consistent and repeatable style?

**Comment by wstrange** [comment]
Hi Hoylen 

I apologize that I have no time these days to  make improvements to dartdap.

I think all of your suggestions sound great. 

Perhaps the best thing would be if I make you a co-contributor to the project. Then you can make direct commits.  Does that work for you?

**Comment by hoylen** [comment]
Warren,

> I think all of your suggestions sound great.
> 
> Perhaps the best thing would be if I make you a co-contributor to the project. Then you can make direct commits. Does that work for you?

Yes, that would work.

One of the things that should be done is to publish a new version to publ.dartlang.org (the current one there is the old 0.0.4). I’m not sure if permissions need to be given there. I’ll give it a go (probably in a few month’s time, to give Dart 1.9.x time to get widely deployed) and contact you if I run into problems.

## Hoylen

http://www.hoylen.com

**Comment by wstrange** [comment]
On the ASN1 parsing - the new transformer code has a lot of ASN1 specific knowledge. Is it possible to use any of the methods in the asn1 library instead? Or perhaps add some  utility methods in that library? It seems to me that any knowledge of ASN1 encoding should be encapsulated in the asn1 lib...

If there are not enough bytes to make a valid ASN1 message - can we detect that by just saying anything less than say 20 bytes (what would the shortest possible LDAP message ever be?) - then just put those bytes on the not processed queue and exit the do loop.  That might be simpler than trying to parse the asn1 header bytes? I guess it has to cover all contingencies.

**Comment by hoylen** [comment]
I can't see any method in _asn1lib_ that was suitable, since they all appear to deal with complete ASN1 objects.

I agree that adding ASN1 encoding related knowledge to _asn1lib_ would be better. Essentially using the code in lines 38-68 from ldap_transformer.dart. Maybe putting that check into all of the "fromBytes" constructors for **all** the different ASN1 objects. Those constructors could throw a new incomplete-message exception if not enough bytes had been passed to them. You'll need a unique exception for it, so that the transformer can catch it and wait for more bytes to arrive.

I wouldn't hard-code 20 bytes into it, especially if it is going into the _asn1lib_ package: legitimate ASN1 objects could be less than 20 bytes long. Even if we are dealing with only LDAP messages, hard-coding 20 bytes would be wrong: for example, if the complete LDAP message was 21 bytes long, trying to parse it when only 20 bytes have arrived in the buffer would still fail.

**Comment by wstrange** [comment]
How would this work as a heuristic:
- Look for at least N bytes, where N == the smallest possible message size. If you have less then this - you dont have a valid LDAP message -might as well wait for more bytes ( I'd think N would be at least 10 - but you could in theory make it less).    
- If you have more than N bytes, then see if you have enough  bytes to make a valid ASN1 object. 

The method   

var x = ASN1Length.decodeLength(bytes);
x.length - tells you how many bytes the object is. If you have less than x.length bytes - not all of the bytes of the ASN1 object have been sent. So put the bytes on the buffer and wait.

**Comment by hoylen** [comment]
**Heuristic**

I'm not seeing how the heuristic makes it easier than implementing it correctly. The heuristic still requires handling the fallback case of "_then seen if you have enough bytes to make a valid ASN1 object_" (which is essentially implementing it correctly).

So just implement it correctly and it's done. That is, I'm saying "if (bytes<N) doA else doB" is better implementation as simply "doB" when the outcome is exactly the same.

**The method**

The method described _currently_ will not work, because the current implementation of _ASN1Length.decodeLength_ assumes there are enough bytes to specify the length. For example, it currently fails when only one byte (the tag) has been received. If _decodeLength_ was fixed, to detect and signal when there aren't enough bytes to even determine how large the object is, this would work.

This approach does depend on the user of _asn1lib_ to check the length before calling any of the ASN1 object constructors. Depending on humans doing the right thing is always risky! But it is certainly an easier and quicker fix than adding the length check to all of the ASN1 constructors to make them safer to use.

Actually, it could work with the current _decodeLength_, if the user was prepared to catch a _RangeError_ exception **and** make an implementation-dependent **assumption** that it will always means "wait for more bytes to arrive". But without specifying this is the behaviour of the _decodeLength_ method, there is no guarantee to the user that this will always work (e.g. a future implementation of _decodeLength_ might throw _RangeError_ in other situations as well). Better to fix _decodeLength_ to have a well defined behaviour when there are insufficient bytes.

This "fix" to _decodeLength_ could simply be documentation (that throwing _RangeError_ is the guaranteed behaviour). But I still think throwing a special "insufficient bytes" exception is much better, since it is hard to promise that _RangeError_ will never ever be thrown in any other situation.

**Comment by chrisridd** [comment]
A useful method for asnlib (read_element?)  would be one that tries to parse a 'partial' block of data, and which tells the caller to read 'n' more bytes. The caller (dartdap) loops (extending the buffer) until read_element returns 0.

read_element would do something like this:
- if no data, return 2 (a tag byte, first length byte)
- if 2 bytes, look at the first length byte:
  - if we have < 0x80 that's the length: return it
  - if it is 0x80 we have indefinite length encoding - can't handle that so give up.
  - if it is 0x81 we need one more byte for the length: return 1
  - if is it 0x82 we need 2 more: return 2
  - if it is 0x83 we need 3 more: return 3
  - if it is 0x84 we need 4 more: return 4
  - otherwise give up
- decode the actual length: return it

So in the best case the caller just needs to issue a read for 2 bytes, and another read to get the rest of the element.

NB this assumes that tags are always one byte. They're not, but in practice (LDAP) they are.

**Comment by hoylen** [comment]
Knowing the number of bytes needed would be useful of we are controlling the reading of the bytes from a file.

In the current implementation of _dartdap_ where the bytes come from a stream, we would only need to know if that number is zero or not. Since we can't control how many bytes the stream will give us next.

For safety, the ASN.1 object constructors and/or _ASN1Length.decodeLength_ should still have some well-defined behaviour if the caller forgets to make this check and passes in insufficient bytes. If that happens, then knowing the number of extra bytes needed is optional.

Since constructors can't return another value, maybe the best approach is to define an "insufficient-bytes" exception class that also indicates the number of bytes that is needed -- the best of both worlds. Let's do that... and implement correct handling of multi-byte tags (though this is really a topic for _asn1lib_ rather than _dartdap_).

**Comment by wstrange** [comment]
OK - does this work?
- If you have 1 byte - save it and wait for more (you just have a tag)
- If you have at least 2 bytes or more:
  - Try to decode the length
  - Be prepared to catch a RangeError (or insufficient bytes as above) exception if the asn1 library can't  decode the length (missing bytes).  If you get this exception, save the bytes and wait for more
- If the length decodes OK - then see if your buffer has that number of bytes.  If yes - then decode the ldap message. Save any left over bytes for the next iteration. If you do not have enough bytes, save the current bytes and wait for more.

Concurrent to this the response timeout should kick in if the library does not see a server response. 

Does the above work?  
The only change that required to asn1 lib is range checking in  decodeLength method

**Comment by wstrange** [comment]
Chris / Hoylen

I just committed a change to a new branch (ldap-transformer) that I think simplifies things a bit. 

The good news is that the asn1lib does not need changing (but I did add a unit test).  The decodeLength method will throw a RangeError when it does not have enough bytes. 

Check out the new transformer and let me know what you think

**Comment by hoylen** [comment]
The parsing bug (1) and documented unit test environment (3) have been addressed by today's commit (19 February 2016).

I'll leave this issue open until I've reformatted the code (item 4) and a refactoring of where and when exceptions are thrown (item 2). There seems to be some inconsistencies in where result codes are returned versus where exceptions are thrown.

**Comment by hoylen** [comment]
The exceptions that are thrown have been tided up (item 2), and the code reformatted using the Dart tools  to ensure consistency (item 4), in pull request #11.

Closing this issue since all the items on it have now been addressed.
